[package]
name = "adelie"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0-only"
description = "Game Boy emulator"
repository = "https://github.com/SnowyMouse/adelie"
readme = "../README.md"
rust-version = "1.79.0"

[dependencies]

[features]
default = ["alloc"]
alloc = []
